export default {
  LOG_IN: '로그인',
  LOG_OUT: '로그아웃',
  LOGIN: 'LogIn',
  LOGOUT: 'LogOut',
  HOME: 'HOME',
  OR: '또는',
  ESSENTIAL: '필수',
  OPTIONAL: '선택',
  AGREE_TERMS: '약관동의',
  AGREE_ALL_TERMS: '약관에 모두 동의',
  TERMS_OF_SERVICE: '서비스 이용약관',
  PRIVACY_POLICY: '개인정보처리방침',
  PRIVACY_AGREE: '개인정보 수집 · 이용 및 제 3자 제공 동의서',
  MARCKETING_AGREE: '마게팅 활용동의',
  ID_EMAIL: '아이디(이메일)',
  PASSWORD: '비밀번호',
  PASSWORD_CONFIRM: '비밀번호 재확인',
  WRONG_EMAIL: '잘못된 이메일 형식입니다.',
  WRONG_PASSWORD: '잘못된 비밀번호 형식입니다.',
  USABLE_EMAIL: '사용 가능한 아이디(이메일) 입니다.',
  USABLE_PASSWORD: '사용 가능한 비밀번호 입니다.',
  MATCH_PASSWORD: '비밀번호가 일치합니다.',
  UN_MATCH_PASSWORD: '비밀번호가 일치하지 않습니다.',
  ID_FIND: '아이디 찾기',
  PASSWORD_FIND: '비밀번호 찾기',
  SIGN_UP: '회원가입',
  ID_SAVE: '아이디 저장',
  APP_SEE: '앱 둘러보기',
  OK: '확인',
  AGREE_TERMS_INFO:
    '신규 서비스 소식, 이벤트 안내, 할인/혜택 등 다양한 정보를 카카오톡,문자,이메일로 받습니다.',
  USER_INFO: '회원정보',
  LOGIN_STATUS_ON: '로그인 상태 유지',
} as const;
