export default {
  ID: '아이디',
  EMAIL: '이메일',
  PASSWORD: '비밀번호',
  PASSWORD_NOT_EQUAL: '비밀번호가 일치하지 않습니다.',
  RECONFIRM: '재확인',
  SIGNIN: '로그인',
  SIGNOUT: '로그아웃',
  SIGNUP: '회원가입',
  REGIST_CAR: '차량등록',
  OPTIONAL: '선택',
  REQUIRED: '필수',
  REQUIRED_FIELD: '필수입력 항목입니다.',
  WRONG_EMAIL_FORM: '잘못된 이메일 형식입니다.',
  WRONG_PASSWORD_FORM: '영문,숫자,특수문자 혼합 6자 이상으로 설정해 주세요.',
  WRONG_ID_OR_PASSWORD: '아이디 혹은 패스워드가 잘못되었습니다',
  AVAILABLE_ID: '사용가능한 아이디(이메일) 입니다.',
  AVAILABLE_PASSWORD: '사용가능한 비밀번호 입니다.',
  PASSWORD_EQUAL: '비밀번호가 일치합니다.',
  REMEMBER_USER: '로그인 상태 유지',
  REMEMBER_ID: '아이디 저장',
  FIND_ID: '아이디 찾기',
  FIND_PASSWORD: '비밀번호 찾기',
  OR: '또는',
  OK: '확인',
  BROWSE_APP: '앱 둘러보기',
  GO_HOME: '홈으로',
  SIGNUP_AGREEMENT: '약관동의',
  SIGNUP_PERSONAL_INFORMATION: '회원정보',
  SIGNUP_AGREE_ALL: '약관에 모두 동의',
  SIGNUP_SERVICE_TERMS: '서비스 이용약관',
  SIGNUP_PRIVACY_POLICY: '개인정보처리방침',
  SIGNUP_PRIVACY_POLICY_AGREE: '개인정보 수집·이용 및 제 3자 제공 동의서',
  SIGNUP_MARKETING_AGREE: '마케팅 활용동의',
  SIGNUP_MARKETING_HELP:
    '신규 서비스 소식, 이벤트 안내, 할인/혜택 등 다양한 정보를 카카오톡, 문자, 이메일로 받겠습니다.',
  SIGNUP_COMPLETE_REGIST: '가입을',
  SIGNUP_COMPLETE_CONGRATULATIONS: '진심으로 축하드립니다.',
  SIGNUP_COMPLETE_REGIST_CAR: '이제 차량을 등록해서',
  SIGNUP_COMPLETE_START_WITH_CARPET: '내 차 관리를 카펫과 함께 시작해보세요.',
};
